### ISSUE TITLE
Bug: Basic Auth for HTTPS Connect not working

### ISSUE THREAD

**Issue by wfjsw** [messiahluo/SmartProxy#10]
According to [HttpConnectTunnel.java#L24](https://github.com/merrickluo/SmartProxy/blob/master/app/src/main/java/me/smartproxy/tunnel/httpconnect/HttpConnectTunnel.java#L24), the  HTTP Basic Auth feature is completely not implemented (which seems available from the config). Could you please fix it?

Code stub that currently work(hack):

```
import android.util.Base64;
```

```
        String auth = m_Config.UserName + ':' + m_Config.Password;
        byte[] bauth = auth.getBytes();
        String request = String
                .format("CONNECT %s:%d HTTP/1.1\r\nProxy-Connection: keep-alive\r\nUser-Agent: %s\r\nX-App-Install-ID: %s\r\nProxy-Authorization: Basic %s\r\n\r\n",
                        m_DestAddress.getHostName(),
                        m_DestAddress.getPort(),
                        ProxyConfig.getInstance().getUserAgent(),
                        ProxyConfig.AppInstallID,
                        Base64.encodeToString(bauth, Base64.DEFAULT));
```

Thanks.

Cheers,
Jabasukuriputo Wang

**Comment by merrickluo** [comment]
Hey, I think you can add a method to check if there is `m_Config.UserName` and `m_Config_Password` and build the header, and make a PR maybe? Or I will do that later.

**Comment by wfjsw** [comment]
Sorry, I am really not a Java programmer (but a Javascript one). ¯\_(ツ)_/¯

**Comment by merrickluo** [comment]
I see...
#12, can you test it out before I merge it?

**Comment by wfjsw** [comment]
Met some NDK problem when building, attempting to fix.
